### ISSUE TITLE
大佬，这个效果可以合成到视频里做特效吗

### ISSUE THREAD

**Issue by microshow** [qjoy/libGDX-Android-AppEffect#4]
如果要合成到视频里，该怎么操作呢

**Comment by qjoy** [comment]
其实视频特效有很多方式，我只谈一下我的思路，我想问题核心是如何操作GPU。首先你了解一下opengl中的shader之后，就会大致明白如何通过gpu进行渲染（这一步理解为屏幕和代操作渲染）。之前团队有个开源项目可以帮助你理解这个问题。
Android https://github.com/LaiFeng-Android/SopCastComponent
